language: java
sudo: false
dist: trusty
group: beta
install: true
addons:
  firefox: "52.0.2"
  apt:
    packages:
    - google-chrome-stable
  sauce_connect:
    username: "MIR_SauceLab"
    access_key: "a7f4c30a-ad90-4d68-82ba-f4fb5e31a8f8"
    no_ssl_bump_domains: "127.0.0.1,localhost"
  apt:
    packages:
    - google-chrome-stable
cache:
  directories:
    - $HOME/.m2/repository
    - geckodriver
env:
  global:
    - MAVEN_OPTS="-Xmx1024M -Xss128M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"
    - GECKODRIVER_VERSION="0.12.0"
    - XVFBARGS=":99 -ac -screen 0 1280x1024x24 -ac +extension GLX +extension RANDR +render -noreset"
    - FIREFOX_BIN=$(which firefox)
    - SELENIUM_BROWSER="chrome"
    - SELENIUM_BROWSERVERSION="58.0"
    - SELENIUM_PLATFORM="Windows 10"
    - SELENIUM_VERSION="3.4.0"
    - SELENIUM_HOST="localhost"
    - SELENIUM_PORT="4445"
    - SAUCE_TRAVIS_BUILDNUMBER=$TRAVIS_BUILD_NUMBER
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- $XVFBARGS"

  # geckodriver
  - |
        export PATH=$PWD/geckodriver:$PATH && \
        if ! type geckodriver > /dev/null 2>&1; then \
            rm -rf geckodriver && \
            mkdir geckodriver && \
            wget https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz -O geckodriver/geckodriver.tar.gz && \
            tar -xvf geckodriver/geckodriver.tar.gz -C geckodriver && \
            rm geckodriver/geckodriver.tar.gz; \
        fi; \
        geckodriver --version

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:$PWD/chromedriver
  - export DISPLAY=:99.0
  - sleep 3
script:
  - mkdir ${HOME}/tmp
  - export TMPDIR="${HOME}/tmp"
#  - mvn -B -P!standard-with-extra-repos -Djetty -DDriverProvider=org.mycore.common.selenium.drivers.MCRChromeDriverFactory clean install && mvn -P!standard-with-extra-repos -B javadoc:javadoc && mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DfailOnMissingReportFile=false
  - mvn -B -P!standard-with-extra-repos -Djetty -DDriverProvider=org.mycore.common.selenium.drivers.MCRRemoteSauceDriverFactory clean install && mvn -P!standard-with-extra-repos -B javadoc:javadoc && mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DfailOnMissingReportFile=false
after_failure:
  - sh travis/autodeploy.sh "$TRAVIS_BUILD_NUMBER-$TRAVIS_EVENT_TYPE-$TRAVIS_PULL_REQUEST" "https://MyCoRe-Travis:$GITHUB_TOKEN@github.com/MyCoRe-Travis/MIR_test_artifacts.git"

