language: java
sudo: false
dist: trusty
group: beta
install: true
addons:
  firefox: "56.0"
  apt:
    packages:
    - google-chrome-stable
    - dbus-x11
cache:
  directories:
    - $HOME/.m2/repository
    - geckodriver
env:
  global:
    - MAVEN_OPTS="-Xmx1024M -Xss128M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"
    - GECKODRIVER_VERSION="0.19.0"
    - CHROMEDRIVER_VERSION=$(curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
    - FIREFOX_BIN=$(which firefox)
    - SELENIUM_BROWSER=firefox
before_install:

  # geckodriver
  - |
        export PATH=$PWD/geckodriver:$PATH && \
        if ! type geckodriver > /dev/null 2>&1; then \
            rm -rf geckodriver && \
            mkdir geckodriver && \
            wget https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz -O geckodriver/geckodriver.tar.gz && \
            tar -xvf geckodriver/geckodriver.tar.gz -C geckodriver && \
            rm geckodriver/geckodriver.tar.gz; \
        fi; \
        geckodriver --version
 
before_script:
  - wget http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:$PWD/chromedriver
script:
  - mkdir ${HOME}/tmp
  - export TMPDIR="${HOME}/tmp"
  - export $(dbus-launch)
  - mvn -B -P!standard-with-extra-repos -Djetty clean install && mvn -P!standard-with-extra-repos -B javadoc:javadoc && mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DfailOnMissingReportFile=false
after_failure:
  - sh travis/autodeploy.sh "$TRAVIS_BUILD_NUMBER-$TRAVIS_EVENT_TYPE-$TRAVIS_PULL_REQUEST" "https://MyCoRe-Travis:$GITHUB_TOKEN@github.com/MyCoRe-Travis/MIR_test_artifacts.git"

