##############################################################################
# Versioned Classifications                                                  #
##############################################################################

# Load a versioned classification via
# update classification from uri xslTransform:versionedLabelsAndIDs:file:.../ORIGIN-versioned.xml

MCR.ContentTransformer.versionedLabels.Class=org.mycore.common.content.transformer.MCRXSLTransformer
MCR.ContentTransformer.versionedLabels.Stylesheet=xsl/mycoreclass-duplicate-versioned-labels.xsl,xsl/mycoreclass-versioned-labels.xsl
MCR.ContentTransformer.versionedLabels.MIMEType=text/xml
MCR.ContentTransformer.versionedLabels.FileExtension=xml

MCR.ContentTransformer.versionedLabelsAndIDs.Class=org.mycore.common.content.transformer.MCRXSLTransformer
MCR.ContentTransformer.versionedLabelsAndIDs.Stylesheet=xsl/mycoreclass-duplicate-versioned-labels.xsl,xsl/mycoreclass-versioned-labels-and-ids.xsl
MCR.ContentTransformer.versionedLabelsAndIDs.MIMEType=text/xml
MCR.ContentTransformer.versionedLabelsAndIDs.FileExtension=xml
