MIR.OAS=MIR.ePuSta
MIR.OAS.GraphProviderURL=MIR.ePuSta.GraphProviderURL
MIR.OAS.Prefix=MIR.ePuSta.Prefix
MIR.Strategy.AccessKey.ObjectTypes=MCR.ACL.AccessKey.Strategy.AllowedObjectTypes
MCR.Access.Strategy.SubmittedCategory=MCR.Access.Strategy.SubmittedCategories
MCR.Migration.ChildrenOrder.Strategy=MCR.Migration.ChildrenOrder.Strategy.Class
MIR.OwnerStrategy.FallbackClass=MIR.OwnerStrategy.Fallback.Class
MIR.Sherpa=MIR.Sherpa.Class
