MIR.OAS=MIR.ePuSta
MIR.OAS.GraphProviderURL=MIR.ePuSta.GraphProviderURL
MIR.OAS.Prefix=MIR.ePuSta.Prefix
MIR.Strategy.AccessKey.ObjectTypes=MCR.ACL.AccessKey.Strategy.AllowedObjectTypes
MCR.Access.Strategy.SubmittedCategory=MCR.Access.Strategy.SubmittedCategories
# needs to be replaced with one property per disabled property type
MIR.Viewer.DisableDerivateType=MCR.Derivate.DisplayFilters.mir.Filter.Filters.20.Mappings.show-file-viewer.[thumbnail,...]
MIR.OwnerStrategy.FallbackClass=MIR.OwnerStrategy.Fallback.Class
MIR.Sherpa=MIR.Sherpa.Class
