MCR.XEditor.DocTypes=MyCoReWizard,MyCoReWebPage


######################################################################
#                                                                    #
#                         Startup and Shutdown                       #
#                                                                    #
######################################################################

MCR.Startup.Class=org.mycore.mir.wizard.MIRWizardStartupHandler,%MCR.Startup.Class%

MCR.ContentTransformer.MyCoReWizard.Class=org.mycore.common.content.transformer.MCRTransformerPipe
MCR.ContentTransformer.MyCoReWizard.Steps=MyCoReWizard_temp,MyCoReWizard_temp2

MCR.ContentTransformer.MyCoReWizard_temp.TransformerFactoryClass=%XALAN%
MCR.ContentTransformer.MyCoReWizard_temp.Stylesheet=xsl/MyCoReWizard.xsl

MCR.ContentTransformer.MyCoReWizard_temp2.Stylesheet=xslt/mir-wizard-layout.xsl
MCR.ContentTransformer.MyCoReWizard_temp2.TransformerFactoryClass=%SAXON%

